### PR TITLE
Folder structure

### PR DESCRIPTION
**Pull request by mirkoeffe**
# Feature PR

### Re-organised the folder structure for route handlers.

Changed the folder structure from having a folder named `routes` with all the different handlers (i.e. `User.routes.ts`), to having for each route handler (i.e. `User`, `UserPosts`) its own folder.
Then for each endpoint it has been created its own file (i.e. `/Users/getAccountInfo.ts` , `/User/getUserById.ts`).

## File Changes

- `fileUploader` router
- `messages` router
- `projectPostReply` router
- `projectPost` router
- `project` router
- `users` router
- `search` router
- `userPosts` router

## Review
- [ ] Tests
- [ ] Documentation

**Reviewer**
- [ ] Code Review
- [ ] Documentation Review

### CODE REVIEW

**Review by jrcopeti — CHANGES_REQUESTED** [review]
Not suitable to merge until bug is solved

**Comment by mirkoeffe** [comment]
Bug has been solved.
The bus was only on the local machine.

**Review by jrcopeti — APPROVED** [review]
nice

**Review by benjamindotdev — APPROVED** [review]
good effort mate

**Pull request merged**
